import ExcelJS from 'exceljs';

export type ExportColumn<T extends object> = {
  header: string;
  key: keyof T | string;
  width?: number;
  /**
   * Optional formatter. Return a primitive that Excel understands.
   */
  value?: (row: T) => string | number | boolean | Date | null | undefined;
  numFmt?: string;
  align?: 'left' | 'center' | 'right';
};

function safeSheetName(name: string) {
  return name
    .replace(/[\\/?*[\]:]/g, ' ')
    .replace(/\s+/g, ' ')
    .trim()
    .slice(0, 31) || 'Sheet1';
}

function toCellValue(v: unknown) {
  if (v === null || v === undefined) return '';
  if (v instanceof Date) return v;
  if (typeof v === 'number' || typeof v === 'string' || typeof v === 'boolean') return v;
  return String(v);
}

type ExportCell = {
  value: unknown;
  font?: unknown;
  alignment?: unknown;
  fill?: unknown;
  border?: unknown;
  numFmt?: string;
};

export async function exportProWorkbook<T extends object>(opts: {
  fileName: string;
  title: string;
  subtitle?: string;
  generatedBy?: string;
  sheetName?: string;
  columns: ExportColumn<T>[];
  rows: T[];
  /** Optional summary rows shown above table. */
  summary?: Array<{ label: string; value: string | number }>;
}): Promise<void> {
  const wb = new ExcelJS.Workbook();
  wb.creator = 'StockSync';
  wb.created = new Date();

  const ws = wb.addWorksheet(safeSheetName(opts.sheetName ?? 'Report'), {
    views: [{ state: 'frozen', ySplit: 6 }],
    properties: { tabColor: { argb: 'FF16A34A' } },
  });

  const colCount = Math.max(1, opts.columns.length);

  // Column config
  ws.columns = opts.columns.map(c => ({
    header: c.header,
    key: c.key as string,
    width: c.width ?? 18,
    style: {
      alignment: {
        vertical: 'middle',
        horizontal: c.align ?? 'left',
        wrapText: true,
      },
      font: { name: 'Calibri', size: 11 },
    },
  }));

  // Title block (rows 1-4)
  ws.mergeCells(1, 1, 1, colCount);
  ws.getCell(1, 1).value = opts.title;
  ws.getCell(1, 1).font = { name: 'Calibri', size: 18, bold: true, color: { argb: 'FF0F172A' } };
  ws.getCell(1, 1).alignment = { vertical: 'middle', horizontal: 'left' };
  ws.getRow(1).height = 26;

  ws.mergeCells(2, 1, 2, colCount);
  ws.getCell(2, 1).value = opts.subtitle ?? '';
  ws.getCell(2, 1).font = { name: 'Calibri', size: 11, color: { argb: 'FF475569' } };
  ws.getCell(2, 1).alignment = { vertical: 'middle', horizontal: 'left' };
  ws.getRow(2).height = 18;

  const meta = [
    `Generated: ${new Date().toLocaleString()}`,
    opts.generatedBy ? `Generated by: ${opts.generatedBy}` : '',
  ].filter(Boolean).join('   •   ');

  ws.mergeCells(3, 1, 3, colCount);
  ws.getCell(3, 1).value = meta;
  ws.getCell(3, 1).font = { name: 'Calibri', size: 10, color: { argb: 'FF64748B' } };
  ws.getCell(3, 1).alignment = { vertical: 'middle', horizontal: 'left' };
  ws.getRow(3).height = 16;

  // Spacer row
  ws.getRow(4).height = 8;

  // Optional summary row(s)
  let tableStartRow = 6;
  if (opts.summary && opts.summary.length) {
    const summaryRow = 5;
    ws.getRow(summaryRow).height = 18;
    const pairs = opts.summary.slice(0, 3); // keep it clean
    const per = Math.max(1, Math.floor(colCount / pairs.length));

    pairs.forEach((p, idx) => {
      const startCol = idx * per + 1;
      const endCol = idx === pairs.length - 1 ? colCount : (idx + 1) * per;
      ws.mergeCells(summaryRow, startCol, summaryRow, endCol);
      const cell = ws.getCell(summaryRow, startCol);
      cell.value = `${p.label}: ${p.value}`;
      cell.font = { name: 'Calibri', size: 11, bold: true, color: { argb: 'FF0F172A' } };
      cell.alignment = { vertical: 'middle', horizontal: 'left' };
      cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFF1F5F9' } };
      cell.border = {
        top: { style: 'thin', color: { argb: 'FFE2E8F0' } },
        left: { style: 'thin', color: { argb: 'FFE2E8F0' } },
        bottom: { style: 'thin', color: { argb: 'FFE2E8F0' } },
        right: { style: 'thin', color: { argb: 'FFE2E8F0' } },
      };
    });
  } else {
    tableStartRow = 5;
  }

  // Table header styling (ExcelJS writes the header row at row=tableStartRow)
  ws.getRow(tableStartRow).values = opts.columns.map(c => c.header);
  ws.getRow(tableStartRow).height = 20;

  for (let c = 1; c <= colCount; c++) {
    const cell = ws.getCell(tableStartRow, c);
    cell.font = { name: 'Calibri', size: 11, bold: true, color: { argb: 'FFFFFFFF' } };
    cell.alignment = { vertical: 'middle', horizontal: 'left' };
    cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FF0F172A' } };
    cell.border = {
      top: { style: 'thin', color: { argb: 'FF0F172A' } },
      left: { style: 'thin', color: { argb: 'FF0F172A' } },
      bottom: { style: 'thin', color: { argb: 'FF0F172A' } },
      right: { style: 'thin', color: { argb: 'FF0F172A' } },
    };
  }

  // Data rows
  const dataStart = tableStartRow + 1;
  opts.rows.forEach((row, idx) => {
    const r = ws.getRow(dataStart + idx);
    r.height = 18;

    opts.columns.forEach((col, cIdx) => {
      const cell = ws.getCell(dataStart + idx, cIdx + 1) as unknown as ExportCell;
      const value = col.value
        ? col.value(row)
        : (row as unknown as Record<string, unknown>)[String(col.key)];
      cell.value = toCellValue(value);

      if (col.numFmt) cell.numFmt = col.numFmt;

      cell.border = {
        top: { style: 'thin', color: { argb: 'FFE2E8F0' } },
        left: { style: 'thin', color: { argb: 'FFE2E8F0' } },
        bottom: { style: 'thin', color: { argb: 'FFE2E8F0' } },
        right: { style: 'thin', color: { argb: 'FFE2E8F0' } },
      };
      cell.alignment = {
        vertical: 'middle',
        horizontal: col.align ?? 'left',
        wrapText: true,
      };
      // Zebra striping
      if (idx % 2 === 1) {
        cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFF8FAFC' } };
      }
    });
  });

  // Auto filter + nice print settings
  ws.autoFilter = {
    from: { row: tableStartRow, column: 1 },
    to: { row: tableStartRow, column: colCount },
  };

  ws.pageSetup = {
    orientation: 'landscape',
    fitToPage: true,
    fitToWidth: 1,
    fitToHeight: 0,
    paperSize: 9,
    showGridLines: false,
    margins: { left: 0.3, right: 0.3, top: 0.5, bottom: 0.5, header: 0.2, footer: 0.2 },
  };

  // Slightly bolder first column for readability
  for (let r = dataStart; r < dataStart + opts.rows.length; r++) {
    ws.getCell(r, 1).font = { name: 'Calibri', size: 11, bold: true, color: { argb: 'FF0F172A' } };
  }

  // Generate file
  const buf = await wb.xlsx.writeBuffer();
  const blob = new Blob([buf], {
    type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
  });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = opts.fileName.endsWith('.xlsx') ? opts.fileName : `${opts.fileName}.xlsx`;
  a.click();
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}
